[package]
name = "beml-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
beml-tree = { path = "../beml-tree" }
fxhash = "0.2.1"
im = "15.1.0"
im-rc = "15.1.0"
thiserror = "1.0.64"
miette = { version = "7.2.0", features = ["fancy"] }
tracing = "0.1.40"
